version: "3"

services:
  image-repo:
    image: "image-repo-app"
    container_name: "image-repo"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo
    container_name: image-repo-db
    ports:
      - "27017:27017"
    volumes:
      - image-repo-data:/data/db

  test-mongo:
    image: mongo
    container_name: image-repo-test-db
    ports:
      - "27018:27017"
    volumes:
      - image-repo-test-data:/data/db

volumes:
  image-repo-data:
    name: image-repo-data
  image-repo-test-data:
    name: image-repo-test-data
